### ISSUE TITLE
Bug - No Jungle Bus attribution anymore

### ISSUE THREAD

**Issue by nlehuby** [Jungle-Bus/VapourTrail#12]
And this comment is deprecated: https://github.com/Jungle-Bus/VapourTrail/blob/master/web/layers.js#L14

**Comment by frodrigo** [comment]
The support of attribution is missing in t-rex, let fix that https://github.com/t-rex-tileserver/t-rex/pull/85

**Comment by frodrigo** [comment]
The `attribution` field is now supported in t-rex master code.

**Comment by nlehuby** [comment]
Let's wait for the next t-rex release + docker update to close this issue :)
