### ISSUE TITLE
Server less version

### ISSUE THREAD

**Issue by frodrigo** [Jungle-Bus/VapourTrail#15]
I build a server less version: 
https://frodrigo.github.io/VapourTrail/web/vapour_trail.html#15.87/43.7363/7.4212

Do you want to integrate this possibility to the project ?
Idea: build cache from t_rex, then use it directly, without postgres and t_rex.

**Comment by nlehuby** [comment]
We may add a few lines in the readme to explain how to generate the tiles and use the project without psql, but it will not work anymore when we will add the API.

But, even if it is not fully working, it would be pretty cool to have this in CI to add some tests. 
For instance, we could configure travis to
* download a small osm pbf
* import and post process the data
* generate the tiles
* push the tiles and the front to the gh-pages branch of the repo

**Comment by frodrigo** [comment]
About the API. Only GET query on resources will be done. So we can also plan to make it static.

**Comment by prhod** [comment]
Adding a  server less use of the project (even only a documentation) is a cool feature ! And enhancing the CI with tests and live demo could help us a lot !

**Comment by frodrigo** [comment]
I made it in my gh-pages branch, but it's not yet an automated task
https://github.com/frodrigo/VapourTrail/commit/1e9a5c28adf94dfd6b9d0e8198c24467c0d646c5

**Comment by prhod** [comment]
yes, I took a look at it (and learned some pretty cool tips ! thanks :+1: )
