### ISSUE TITLE
Start the API

### ISSUE THREAD

**Issue by nlehuby** [Jungle-Bus/VapourTrail#20]
We need an API to support the map interactions.

As a start, we need one or many endpoints with route info :
* list of stops, in the right order
* list of other routes from this line (route_master relation)
* geometries
* route metadata (tags from the route relation)

**Comment by frodrigo** [comment]
About the geometries. The actual implementation use segments from tiles and display of a route only need the segment ids.

**Comment by frodrigo** [comment]
Which kind of tech do you want for the API ?
I'm seriously think of using none ! Static json files dumped from the database can do the job.
What do you think ?

**Comment by prhod** [comment]
Your PR seems great, but personally, I'm not so found of SQL, I prefer Python :p

**Comment by prhod** [comment]
We discussed the matter and we agreed on : 
- one endpoint "/route/<osm_id>"
- it returns : 
  - the route meta data
  - the geojson of the ways 
  - the geojson of the stop_positions
  - a list of stops in the right order as proposed in the mock and with a property `available_interchanges`

**Comment by frodrigo** [comment]
I'm persist in thinking the top level of the json should be valid geojson to be reused directly in other applications. Think to web map, umap....

**Comment by prhod** [comment]
Digging a little further, it could be something like that : 
- a Feature containing
  - Feature.propetries with the route properties
  - the Multi-Linestring geometry of the route (aka the ways)
  - a FeatureCollection containing the stop_positions as a collection of Points 
  - the list of stops in the right order as proposed in the mock and with a property `available_interchanges`
- the attribution of the API

What do you think ?

**Comment by frodrigo** [comment]
The structure of geojson is not free, you can't nest thing like you want. FeatureCollection must be a t top level.

**Comment by prhod** [comment]
Thanks for the warning. I've checked in https://tools.ietf.org/html/rfc7946#section-3.2, and I don't see saying GeoJSON objects cannot be nested.
It is stated in chapter 3 that `A GeoJSON object is a JSON object.`, and in chapter 3-2 : 
`A Feature object has a member with the name "properties".  The  value of the properties member is an object (any JSON object or a  JSON null value)`.
It implies a property value can be a GeoJSON object.
It's true that most other softwares won't be able to access this information and we will probably need other endpoints... but that is an other story ^^

**Comment by prhod** [comment]
I think we can close this issue with https://github.com/Jungle-Bus/VapourTrail/pull/40.
I've moved the discussion about the second endpoint to this new issue: https://github.com/Jungle-Bus/VapourTrail/issues/41

**Comment by prhod** [comment]
As indicated, i'm closing this issue as https://github.com/Jungle-Bus/VapourTrail/pull/40 has been merged. Further improvements are expected later, especially with the discussion in https://github.com/Jungle-Bus/VapourTrail/issues/41.
