### ISSUE TITLE
Import error - distance returned negative

### ISSUE THREAD

**Issue by prhod** [Jungle-Bus/VapourTrail#37]
Trying to import the france Geofabrik export of 31 of may, i've ended with the following error:
`psql:/mapping/post-process-internal.sql:40: ERROR:  distance returned negative!`

The previous fix was made there: 
https://github.com/Jungle-Bus/VapourTrail/commit/37803d03e4aa817e6453b1f2ee5d14edb565ff40

**Comment by frodrigo** [comment]
I have no enough free space on my computer to run France. Can you identify which OSM object cause this issue ?

**Comment by prhod** [comment]
For rel_osm_id `-3135814` , after import, this query returns `POLYGON EMPTY` for all geoms
```sql
    SELECT rel_osm_id,  member_index,  st_astext(geom),
    FROM  osm_relation_members_route
    WHERE
      osm_relation_members_route.member_role LIKE '%stop%'
      and rel_osm_id = -3135814```
Searching for the object in OSM, i found that all stop members of this relation are relations :'(
https://www.openstreetmap.org/relation/3135814
What do you thing of ignoring `relation` members with role `stop` ?

**Comment by frodrigo** [comment]
I think we can ignore route without loaded geometry or, better, support relation as stop.

**Comment by frodrigo** [comment]
Fix the distance computation issue.

**Comment by frodrigo** [comment]
@prhod what is the issue with relation as stop, there are already ignored, doesn't ?

**Comment by prhod** [comment]
sorry, it seems I misunderstood the problem :p Thanks for the fix, I'll try it tonight if I can.
